### PR TITLE
Fix returning tasks

### PR DESCRIPTION
**Pull request by GerardSmit**
Fix rewriting the return statement when the task is directly returned from an expression.

# With a body
```cs
[CreateSyncVersion]
private ValueTask ReturnAsync(bool input)
{
    if (input)
    {
        return ReturnAsync();
    }
    return ReturnAsync();
}

private ValueTask ReturnAsync() => default;
private void Return() { }
```

## Before
Invalid because the `Return`-method returns `void`.
```cs
private void Return(bool input)
{
    if (input)
    {
        return Return();
    }
    return Return();
}
```

## After
```cs
private void Return(bool input)
{
    if (input)
    {
        Return(); return;
    }
    Return();
}
```

# Without a body
```cs
[CreateSyncVersion]
private ValueTask ReturnAsync(bool input)
{
    if (input) return ReturnAsync();
    return ReturnAsync();
}

private ValueTask ReturnAsync() => default;
private void Return() { }
```

## Before
Invalid because the `Return`-method returns `void`.
```cs
private void Return(bool input)
{
    if (input) return Return();
    return Return();
}
```

## After
```cs
private void Return(bool input)
{
    if (input) { Return(); return; }
    Return();
}
```

### CODE REVIEW

**Comment by GerardSmit** [comment]
One more thing I need to check: whether the expression is being dropped if it's `default` or Task.CompletedTask (in the if-statement, direct in the root of the method works). 

I'll add a unit test for this tomorrow.

**Comment by virzak** [comment]
My first thought is that `Return(); return;` should be changed to `Return();` What do you think?

**Comment by GerardSmit** [comment]
Makes sense. I'll see if I can detect whether the parent is the root body of the method.

Out of my head: the only thing that could go wrong is if you use `goto`:

```cs
Task SomeMethodAsync()
{
    goto SkipReturn;
    Console.WriteLine("Wrong...");
    return Task.CompletedTask;
    
SkipReturn:
    Console.WriteLine("Correct!");
    return Task.CompletedTask;
}
```

This would compile into the following if we would remove the return and skip everything after it:

```cs
void SomeMethod()
{
    goto SkipReturn;
    Console.WriteLine("Wrong...");
}
```

But I doubt anyone is using labels and goto's, especially in their async-methods.

**Comment by GerardSmit** [comment]
Should be all good now. The last return is getting removed now.

Also, the returns in child blocks were broken and has fixed in the last commit:

```cs
[CreateSyncVersion]
private ValueTask ReturnAsync(bool input)
{
    if (input)
    {
        return default;
    }
    Console.WriteLine("123");
    return default;
}
```

## Before
```cs
private void Return(bool input)
{
    if (input)
    {
        default; return;
    }
    global::System.Console.WriteLine("123");
}
```

## After
```cs
private void Return(bool input)
{
    if (input)
    {
        return;
    }
    global::System.Console.WriteLine("123");
}
```

**Comment by GerardSmit** [comment]
Last commits fixes conditional returns.

# Conditional
```cs
[CreateSyncVersion]
private ValueTask ReturnAsync(bool input)
{
    return input ? ReturnAsync() : ReturnAsync();
}

private ValueTask ReturnAsync() => ReturnAsync();
private void Return() { }
```

## Before
```cs
private void Return(bool input)
{
    input ? Return() : Return();
}
```

## After
```cs
private void Return(bool input)
{
    if (input) Return(); else Return();
}
```

# Only true
```cs
[CreateSyncVersion]
private ValueTask ReturnTrueAsync(bool input)
{
    return input ? ReturnAsync() : default;
}

private ValueTask ReturnAsync() => default;
private void Return() { }
```

## Before
```cs
private void ReturnTrue(bool input)
{
    input ? Return() : default;
}
```

## After
```cs
private void ReturnTrue(bool input)
{
    if (input) Return();
}
```

# Only false
## Before
```cs
private void ReturnFalse(bool input)
{
    input ? default : Return();
}
```

## After
```cs
private void ReturnFalse(bool input)
{
    if (!input) Return();
}
```

**Comment by virzak** [comment]
Thanks so much. Will review this week.

**Comment by virzak** [comment]
Thanks so much, @GerardSmit . Apologies for the delay.

**Pull request merged**
